import { supabase } from '@/lib/supabaseClient';
import type { CampaignRule, CampaignRuleInput } from '@/lib/types';

interface DeletedRuleCampaign {
  date: string;
  state: string;
  place: string;
  site: string;
  time: string;
  leader: string;
}

interface GetRulesOptions {
  adminStatus: string | null;
  userState: string | null;
  userLeader: string | null;
}

export async function getRules({
  adminStatus,
  userState,
  userLeader,
}: GetRulesOptions): Promise<CampaignRule[]> {
  const isTeamLeader = adminStatus !== 'AD' && adminStatus !== 'SR' && !!userState;
  const isStateReporter = adminStatus === 'SR';

  if (isTeamLeader && !userLeader) return [];

  let query = supabase.from('campaign_rules').select('*');

  if (isStateReporter && userState) {
    query = query.eq('state', userState.toUpperCase().trim());
  }
  if (isTeamLeader && userState && userLeader) {
    query = query.eq('state', userState.toUpperCase().trim()).eq('leader', userLeader);
  }

  const { data, error } = await query
    .order('priority', { ascending: false })
    .order('created_at', { ascending: false });

  if (error) throw error;
  return (data || []) as CampaignRule[];
}

export async function createRule(
  ruleData: CampaignRuleInput,
  createdBy: string,
): Promise<void> {
  const { error } = await supabase
    .from('campaign_rules')
    .insert([{ ...ruleData, created_by: createdBy }]);
  if (error) throw error;
}

export async function updateRule(
  id: string,
  ruleData: Partial<CampaignRuleInput>,
): Promise<void> {
  const { error } = await supabase.from('campaign_rules').update(ruleData).eq('id', id);
  if (error) throw error;
}

export async function deleteRule(id: string): Promise<void> {
  const { error } = await supabase.from('campaign_rules').delete().eq('id', id);
  if (error) throw error;
}

export async function setRuleActive(id: string, isActive: boolean): Promise<void> {
  const { error } = await supabase
    .from('campaign_rules')
    .update({ is_active: isActive })
    .eq('id', id);
  if (error) throw error;
}

/**
 * Record a rule exception so a manually-deleted, rule-generated campaign is never
 * silently regenerated by a later weekly refresh (see #93 investigation — the refresh's
 * dedup only checks whether a matching row currently exists, so a deletion was
 * indistinguishable from "never generated" and got recreated).
 *
 * Matches the deleted campaign back to its originating rule(s) by state/place/site/leader
 * plus effective time (accounting for a per-date `override_fields` time override, since the
 * stored campaign keeps the override value while `rule.time` stays the rule's default), then
 * appends the campaign's date to that rule's `rule_config.exceptions` — the same list
 * `isDateExcepted` in campaignRules.ts already filters out during evaluation.
 *
 * Best-effort: errors are logged, never thrown, so a lookup/update failure here must not
 * block the campaign deletion itself.
 */
export async function excludeDateForDeletedCampaign(campaign: DeletedRuleCampaign): Promise<void> {
  try {
    const { data: candidateRules, error } = await supabase
      .from('campaign_rules')
      .select('id, time, rule_config')
      .eq('state', campaign.state)
      .eq('place', campaign.place)
      .eq('site', campaign.site)
      .eq('leader', campaign.leader);
    if (error) throw error;

    const matches = ((candidateRules || []) as Pick<CampaignRule, 'id' | 'time' | 'rule_config'>[]).filter(
      (rule) => {
        const overrideTime = rule.rule_config?.override_fields?.[campaign.date]?.time;
        const effectiveTime = typeof overrideTime === 'string' ? overrideTime : rule.time;
        return effectiveTime === campaign.time;
      },
    );

    for (const rule of matches) {
      const exceptions = rule.rule_config?.exceptions ?? [];
      if (exceptions.includes(campaign.date)) continue;

      const { error: updateError } = await supabase
        .from('campaign_rules')
        .update({ rule_config: { ...rule.rule_config, exceptions: [...exceptions, campaign.date] } })
        .eq('id', rule.id);
      if (updateError) throw updateError;
    }
  } catch (err) {
    console.error('[rulesService] Failed to record deletion exception:', err);
  }
}
