/* Replays the weeklyRefreshService + campaignRules logic in plain JS against the
 * real DB (read-only) to see exactly what toInsert would contain, so we can check
 * for in-batch duplicate rows (same slot key generated by both the normal pass and
 * the catch-up pass) that would inflate the reported "created" count.
 *
 * This is a faithful port of lib/campaignDates.ts + lib/campaignRules.ts +
 * lib/services/weeklyRefreshService.ts as of the current codebase — read-only,
 * makes no writes.
 */
const fs = require('fs');
const path = require('path');
const envPath = path.join(__dirname, '..', '.env.local');
fs.readFileSync(envPath, 'utf-8').split('\n').forEach((line) => {
  const t = line.trim();
  if (!t || t.startsWith('#')) return;
  const [k, ...rest] = t.split('=');
  if (k && rest.length) process.env[k.trim()] = rest.join('=').trim().replace(/^["']|["']$/g, '');
});
const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

async function rest(pathAndQuery) {
  const res = await fetch(`${url}/rest/v1/${pathAndQuery}`, {
    headers: { apikey: key, Authorization: `Bearer ${key}` },
  });
  if (!res.ok) { console.error('ERROR', pathAndQuery, res.status, await res.text()); return []; }
  return res.json();
}

// ---- campaignDates.ts port ----
function getMondayOfWeek(date, weeksOffset = 0) {
  const result = new Date(date);
  const dayOfWeek = result.getDay();
  const daysToMonday = dayOfWeek === 0 ? 6 : dayOfWeek - 1;
  result.setDate(result.getDate() - daysToMonday + weeksOffset * 7);
  result.setHours(0, 0, 0, 0);
  return result;
}
function calculateCampaignDates(referenceDate) {
  const dayOfWeek = referenceDate.getDay();
  let pastCampaignStart, upcomingCampaignStart;
  if (dayOfWeek >= 4 || dayOfWeek === 0) pastCampaignStart = getMondayOfWeek(referenceDate, 0);
  else pastCampaignStart = getMondayOfWeek(referenceDate, -1);
  if (dayOfWeek >= 1 && dayOfWeek <= 6) upcomingCampaignStart = getMondayOfWeek(referenceDate, 0);
  else upcomingCampaignStart = getMondayOfWeek(referenceDate, 1);
  const secondWeekStart = new Date(upcomingCampaignStart);
  secondWeekStart.setDate(secondWeekStart.getDate() + 7);
  return { pastCampaignStart, upcomingCampaignStart, secondWeekStart };
}
function formatDateForDb(date) {
  const y = date.getFullYear(), m = String(date.getMonth() + 1).padStart(2, '0'), d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

// ---- campaignRules.ts port ----
function findWeeklyOccurrences(dayOfWeek, startDate, endDate) {
  const matches = [];
  const current = new Date(startDate);
  const diff = (dayOfWeek - current.getDay() + 7) % 7;
  current.setDate(current.getDate() + diff);
  while (current <= endDate) { matches.push(new Date(current)); current.setDate(current.getDate() + 7); }
  return matches;
}
function findMonthlyOccurrences(weekNumber, dayOfWeek, startDate, endDate) {
  if (dayOfWeek === null) return [];
  const matches = [];
  const cursor = new Date(startDate.getFullYear(), startDate.getMonth(), 1);
  while (cursor <= endDate) {
    const year = cursor.getFullYear(), month = cursor.getMonth();
    let targetDate = null;
    if (weekNumber === -1) {
      const lastDay = new Date(year, month + 1, 0);
      let daysBack = lastDay.getDay() - dayOfWeek; if (daysBack < 0) daysBack += 7;
      targetDate = new Date(year, month, lastDay.getDate() - daysBack);
    } else {
      const firstDayOfMonth = new Date(year, month, 1).getDay();
      let daysToFirst = dayOfWeek - firstDayOfMonth; if (daysToFirst < 0) daysToFirst += 7;
      const nthDay = 1 + daysToFirst + (weekNumber - 1) * 7;
      const daysInMonth = new Date(year, month + 1, 0).getDate();
      if (nthDay <= daysInMonth) targetDate = new Date(year, month, nthDay);
    }
    if (targetDate && targetDate >= startDate && targetDate <= endDate) matches.push(targetDate);
    cursor.setMonth(cursor.getMonth() + 1);
  }
  return matches;
}
function findBiweeklyOccurrences(frequencyValue, dayOfWeek, startDate, endDate, referenceDate) {
  const matches = [];
  const msPerPeriod = frequencyValue * 7 * 24 * 60 * 60 * 1000;
  const normStart = new Date(startDate); normStart.setHours(0, 0, 0, 0);
  const normEnd = new Date(endDate); normEnd.setHours(23, 59, 59, 999);
  let anchor;
  if (referenceDate) {
    const [y, m, d] = referenceDate.split('-').map(Number);
    anchor = new Date(y, m - 1, d); anchor.setHours(0, 0, 0, 0);
    if (anchor.getDay() !== dayOfWeek) anchor.setDate(anchor.getDate() + (dayOfWeek - anchor.getDay() + 7) % 7);
  } else {
    anchor = new Date(normStart);
    anchor.setDate(anchor.getDate() + (dayOfWeek - anchor.getDay() + 7) % 7);
  }
  let firstInRange;
  if (anchor <= normStart) {
    const periods = Math.ceil((normStart.getTime() - anchor.getTime()) / msPerPeriod);
    firstInRange = new Date(anchor.getTime() + periods * msPerPeriod);
  } else {
    const periods = Math.floor((anchor.getTime() - normStart.getTime()) / msPerPeriod);
    const candidate = new Date(anchor.getTime() - periods * msPerPeriod);
    firstInRange = candidate >= normStart ? candidate : anchor;
  }
  let current = new Date(firstInRange);
  while (current <= normEnd) { matches.push(new Date(current)); current = new Date(current.getTime() + msPerPeriod); }
  return matches;
}
function isDateInRange(date, startDate, endDate) {
  if (startDate && date < new Date(startDate + 'T00:00:00')) return false;
  if (endDate && date > new Date(endDate + 'T00:00:00')) return false;
  return true;
}
function isDateExcepted(date, ruleConfig) {
  if (!ruleConfig?.exceptions?.length) return false;
  const y = date.getFullYear(), m = String(date.getMonth() + 1).padStart(2, '0'), d = String(date.getDate()).padStart(2, '0');
  return ruleConfig.exceptions.includes(`${y}-${m}-${d}`);
}
function evaluateRule(rule, targetStartDate, targetEndDate) {
  if (!rule.is_active) return [];
  let matchingDates = [];
  switch (rule.frequency_type) {
    case 'monthly':
      if (rule.month_week_number === null || rule.month_day_of_week === null) return [];
      matchingDates = findMonthlyOccurrences(rule.month_week_number, rule.month_day_of_week, targetStartDate, targetEndDate);
      break;
    case 'biweekly': {
      if (rule.day_of_week === null || rule.frequency_value === null) return [];
      const refDate = rule.rule_config?.reference_date ?? null;
      matchingDates = findBiweeklyOccurrences(rule.frequency_value, rule.day_of_week, targetStartDate, targetEndDate, refDate);
      break;
    }
    case 'weekly':
      if (rule.day_of_week === null) return [];
      matchingDates = findWeeklyOccurrences(rule.day_of_week, targetStartDate, targetEndDate);
      break;
    default: return [];
  }
  const validDates = matchingDates.filter(date => isDateInRange(date, rule.start_date, rule.end_date) && !isDateExcepted(date, rule.rule_config));
  return validDates.map(date => {
    const y = date.getFullYear(), m = String(date.getMonth() + 1).padStart(2, '0'), d = String(date.getDate()).padStart(2, '0');
    const dateStr = `${y}-${m}-${d}`;
    const overrideFields = rule.rule_config?.override_fields?.[dateStr] ?? {};
    return {
      date: dateStr, state: rule.state, place: rule.place, site: rule.site,
      time: typeof overrideFields.time === 'string' ? overrideFields.time : rule.time,
      leader: rule.leader, mobile: rule.mobile, category: 'TWOL', rule_id: rule.id,
    };
  });
}
function evaluateRules(rules, targetStartDate, targetEndDate) {
  const sortedRules = [...rules].sort((a, b) => b.priority - a.priority);
  const seen = new Map(); const all = [];
  for (const rule of sortedRules) {
    for (const campaign of evaluateRule(rule, targetStartDate, targetEndDate)) {
      const key = `${campaign.date}_${campaign.state}_${campaign.place}_${campaign.time}`;
      if (!seen.has(key)) { seen.set(key, campaign); all.push(campaign); }
    }
  }
  return all;
}

// ---- weeklyRefreshService.ts replay (read-only), for a given "now" ----
async function replay(nowLabel, referenceDate, existingSnapshot, allRules) {
  const { upcomingCampaignStart, secondWeekStart, pastCampaignStart } = calculateCampaignDates(referenceDate);
  const secondWeekEnd = new Date(secondWeekStart); secondWeekEnd.setDate(secondWeekEnd.getDate() + 6);
  const catchUpEnd = new Date(secondWeekStart); catchUpEnd.setDate(catchUpEnd.getDate() - 1);
  const secondWeekEndStr = formatDateForDb(secondWeekEnd);
  const pastCampaignStartStr = formatDateForDb(pastCampaignStart);

  console.log(`\n===== Replay for ${nowLabel} (reference=${referenceDate.toISOString()}) =====`);
  console.log('pastCampaignStart:', formatDateForDb(pastCampaignStart), 'upcomingCampaignStart:', formatDateForDb(upcomingCampaignStart),
    'secondWeekStart:', formatDateForDb(secondWeekStart), 'secondWeekEnd:', secondWeekEndStr, 'catchUpEnd:', formatDateForDb(catchUpEnd));

  const existingRows = existingSnapshot.filter(c => c.date >= pastCampaignStartStr && c.date <= secondWeekEndStr);
  const existingSlotKeys = new Set(existingRows.map(c => `${c.date}_${c.state}_${c.place}_${c.site}_${c.time}_${c.leader}`));
  const ruleSlotKey = r => `${r.state}_${r.place}_${r.site}_${r.time}_${r.leader}`;
  const existingRuleSlotKeys = new Set(existingRows.map(c => ruleSlotKey(c)));

  const states = Array.from(new Set(allRules.map(r => r.state)));
  const allNewCampaigns = [];
  for (const state of states) {
    const stateRules = allRules.filter(r => r.state === state);
    const ruleCampaigns = evaluateRules(stateRules, secondWeekStart, secondWeekEnd);
    allNewCampaigns.push(...ruleCampaigns.map(c => ({ ...c, pass: 'normal' })));

    const catchUpRules = stateRules.filter(r => !existingRuleSlotKeys.has(ruleSlotKey(r)));
    if (catchUpRules.length > 0) {
      const catchUpCampaigns = evaluateRules(catchUpRules, upcomingCampaignStart, catchUpEnd);
      allNewCampaigns.push(...catchUpCampaigns.map(c => ({ ...c, pass: 'catchup' })));
    }
  }

  const slotKey = c => `${c.date}_${c.state}_${c.place}_${c.site}_${c.time}_${c.leader}`;
  const toInsert = allNewCampaigns.filter(c => !existingSlotKeys.has(slotKey(c)));
  console.log('allNewCampaigns:', allNewCampaigns.length, ' toInsert (would create):', toInsert.length, ' skipped:', allNewCampaigns.length - toInsert.length);

  // Check for in-batch duplicate slot keys within toInsert itself
  const seenSlots = new Map();
  const dupes = [];
  for (const c of toInsert) {
    const k = slotKey(c);
    if (seenSlots.has(k)) dupes.push({ key: k, a: seenSlots.get(k), b: c });
    else seenSlots.set(k, c);
  }
  console.log('IN-BATCH DUPLICATE slot keys inside toInsert:', dupes.length);
  if (dupes.length) console.log(JSON.stringify(dupes, null, 2));

  console.table(toInsert.map(c => ({ date: c.date, state: c.state, place: c.place, site: c.site, time: c.time, leader: c.leader, pass: c.pass })));
  return { toInsert, catchUpEnd, secondWeekEnd, pastCampaignStart, upcomingCampaignStart, secondWeekStart };
}

(async () => {
  const allRules = await rest('campaign_rules?select=*&is_active=eq.true&order=priority.desc');
  // Use a broad snapshot of campaigns (current state; nothing has been deleted since the incident)
  const allCampaigns = await rest('campaigns?select=date,state,place,site,time,leader,created_at&order=date.asc');
  console.log('active rules:', allRules.length, ' campaigns in table:', allCampaigns.length);

  // auto run reference: 2026-07-19T01:22:06Z (UTC) — server-side cron, so use UTC as-is
  await replay('AUTO 2026-07-19 (as run, using campaigns snapshot BEFORE that run)',
    new Date('2026-07-19T01:22:06Z'),
    allCampaigns.filter(c => c.created_at < '2026-07-19T01:22:06'),
    allRules);

  // manual run reference: 2026-07-21T11:52:30Z (UTC timestamp of insert) -> convert perspective as AEST local same day
  await replay('MANUAL 2026-07-21 (as run, using campaigns snapshot BEFORE that run)',
    new Date('2026-07-21T11:52:30Z'),
    allCampaigns.filter(c => c.created_at < '2026-07-21T11:52:30'),
    allRules);
})();
